### ISSUE TITLE
Icone onglet site

### ISSUE THREAD

**Issue by leooryr76** [nsi-corneille/nsi-corneille.github.io#1]
https://www.delftstack.com/fr/howto/html/html-tab-icon/

**Comment by leooryr76** [comment]
correction commit

**Comment by leooryr76** [comment]
Icone ajoutée

**Comment by leooryr76** [comment]
changement commit

**Comment by O4h** [comment]
Réglé dans https://github.com/nsi-corneille/nsi-corneille.github.io/commit/6ab0c150b84c4d9a9154efbdf132fc1fd79a0da8 !
